### ISSUE TITLE
Add this Project To Hacktober Fest

### ISSUE THREAD

**Issue by Rohan1904** [Rishikesh-12/HacktoberFest2020#397]
Its showing Invalid Repo .

**Comment by Rishikesh-12** [comment]
You might have made some error.
Kindly follow the procedure mentioned in the README.md and make a pull request.
We will be happy to merge your pull request.

**Comment by Parthadhwaj** [comment]
Please check merge request #371 and revert back. Thanks :).

**Comment by PrajaktaSathe** [comment]
Does my PR #562 need to be merged for it to be accepted for the Hacktoberfest 2020, which is currently going on? If yes, could you please merge it? Sorry, I am a beginner to open source.
Thanks a lot!
