### ISSUE TITLE
What To Contribute?

### ISSUE THREAD

**Issue by Siddhant-K-code** [Rishikesh-12/HacktoberFest2020#54]
What Type of Projects/ Programs, we can add ?

Can i add react projects ?

**Comment by Rishikesh-12** [comment]
Yes that would be great.

**Comment by Siddhant-K-code** [comment]
@Rishikesh-12 i also make a PRs regarding Searching and Sorting Algorithms in C++ , pls review and merge it

**Comment by Rishikesh-12** [comment]
Are your pull requests merged yet?
if not please mention your pull request numbers.

**Comment by Siddhant-K-code** [comment]
@Rishikesh-12 yes, all My PRs are merged, thanks

**Comment by rhys1998** [comment]
#329 I have added a HTML project .

**Comment by dishantvyas15** [comment]
Hello @navneetsn18 !
Can I contribute to this repo by adding an OOP based C++ sorting algorithm ??

**Comment by slytherin20** [comment]
@Rishikesh-12 I have added a PR for a Js project which uses Github API and fetches the repository for a user. Please review it and merge it if it is fine. PR number- #571

**Comment by BRZ-OS** [comment]
Hi @Rishikesh-12 ! can I contribute this repo for hacktoberfest? 
I would like to add a mini-project about using JS & API get lyrics project

**Comment by deadline007** [comment]
> Hello @navneetsn18 !
> Can I contribute to this repo by adding an OOP based C++ sorting algorithm ??

Kem cho @dishantvyas15 ,
You can contribute in any way you like.

**Comment by deadline007** [comment]
> Hi @Rishikesh-12 ! can I contribute this repo for hacktoberfest?
> I would like to add a mini-project about using JS & API get lyrics project

We would love to see you contribute with that.

**Comment by deadline007** [comment]
> @Rishikesh-12 I have added a PR for a Js project which uses Github API and fetches the repository for a user. Please review it and merge it if it is fine. PR number- #571

Your Pull request has been accepted and merged.

**Comment by anchal-gupta** [comment]
@Rishikesh-12 and @deadline007 , I have recently contributed by making a PR for "To-Do List" using HTML, CSS and JS. I have also included a readme.md file to make you understand primary purpose of application. Please review and merge if it is fine ! :)

**Comment by dishantvyas15** [comment]
@deadline007 Maja ma!
I've just made a pull request (#590) for contributing a couple of files.
Requesting to review and merge it!

**Comment by Rishikesh-12** [comment]
> @Rishikesh-12 and @deadline007 , I have recently contributed by making a PR for "To-Do List" using HTML, CSS and JS. I have also included a readme.md file to make you understand primary purpose of application. Please review and merge if it is fine ! :)

what is the pull request number?

**Comment by Rishikesh-12** [comment]
> @deadline007 Maja ma!
> I've just made a pull request (#590) for contributing a couple of files.
> Requesting to review and merge it!

Accepted and merged

**Comment by kavita121** [comment]
Please merge mine #597

**Comment by bighnesh0404** [comment]
> Are your pull requests merged yet?
> if not please mention your pull request numbers.

pull request 601 is about a c program for Time Complexity plot of Bubble, Insertion and Selection sort

**Comment by anchal-gupta** [comment]
> > @Rishikesh-12 and @deadline007 , I have recently contributed by making a PR for "To-Do List" using HTML, CSS and JS. I have also included a readme.md file to make you understand primary purpose of application. Please review and merge if it is fine ! :)
> 
> what is the pull request number?

#581

**Comment by BRZ-OS** [comment]
Hi, @deadline007 thank you!
just contribute it, mine is #605, and please review it and merge if it is ok!

**Comment by deadline007** [comment]
> > > @Rishikesh-12 and @deadline007 , I have recently contributed by making a PR for "To-Do List" using HTML, CSS and JS. I have also included a readme.md file to make you understand primary purpose of application. Please review and merge if it is fine ! :)
> > 
> > 
> > what is the pull request number?
> 
> #581

Accepted and merged

**Comment by deadline007** [comment]
> Hi, @deadline007 thank you!
> just contribute it, mine is #605, and please review it and merge if it is ok!

Accepted and merged.

**Comment by Aniruddhmuley2001** [comment]
Hello @deadline007 @Rishikesh-12 have made a pull request #614 to add Sieve of Eratosthenes Algorithm, please do review the PR and merge, if works well.
