### ISSUE TITLE
Typos in the Readme.md

### ISSUE THREAD

**Issue by parthpanchal123** [Rishikesh-12/HacktoberFest2020#85]

**Comment by Rishikesh-12** [comment]
Can you be more specific?

**Comment by parthpanchal123** [comment]
Typos such as brach-name,  HactoberFest2020 etc have to be fixed in the readme file

**Comment by parthpanchal123** [comment]
Should I quickly fix it ?

**Comment by Siddhant-K-code** [comment]
@parthpanchal123 i did it and raised a PR any more typo's are there ?

**Comment by parthpanchal123** [comment]
@Siddhant-K-code can you mention the pr number ?

**Comment by Siddhant-K-code** [comment]
it is merged now, you can check the updated README, please let us know if there any more Issues/errors

**Comment by parthpanchal123** [comment]
Yea sure :)

**Comment by Rishikesh-12** [comment]
Thanks for your contributions @parthpanchal123 and @Siddhant-K-code
